FROM node-vue-builder-20 AS build-stage

WORKDIR /app

COPY ./front .

RUN npm install
RUN npm run build

# stage 2
FROM nginx:alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
