FROM node-vue-builder-20 as build-stage

WORKDIR /app

COPY ./front .

RUN npm install
RUN npm run build

# stage 2
FROM nginx:alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
